# Generated by Django 6.1.1 on 2026-09-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
